require('plugins')
require('keymappings')
require('settings')
require('variables')
--require('nv-compe')
--require('lsp')
require('tree-sitter')
require('telescope-plugin')
require('gitsigns-plugin')

